name: Create release

on:
  workflow_dispatch:
    inputs:
      tag:
        # tag version to use for release 
        description: 'Tag version'
        required: true
      title:
        # Release title
        description: 'Release title'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build using Ant
        run: ant dist
