name: Set variables

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to display'
        default: 'Hello world'
        required: true

jobs:
  set_variables:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: echo $MESSAGE
        env:
          MESSAGE: "[LOG MESSAGE] ${{ github.event.inputs.message }}"
