name: Set variables

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to display'
        default: 'Hello world'
        required: true
      other_message:
        description: 'Optional message'

jobs:
  set_variables:
    runs-on: ubuntu-latest

    steps:
      # Conditional set variable
      - name: Setup variables
        if: "${{ github.event.inputs.other_message }}"
        run: echo MSG="[SECOND MESSAGE] ${{ github.event.inputs.other_message }}" >> $GITHUB_ENV 

      # Set environement for step
      - name: Simple env usage
        run: echo $MESSAGE
        env:
          MESSAGE: "[LOG MESSAGE] ${{ github.event.inputs.message }}"
      - name: Second message
        if: ${{ env.MSG != '' }}
        run: echo $MSG
