name: Set variables

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to display'
        default: 'Hello world'
        required: true
      other_message:
        description: 'Optional message'

jobs:
  set_variables:
    runs-on: ubuntu-latest

    steps:
      # Set environement for step
      - name: Simple env usage
        run: echo $MESSAGE
        env:
          MESSAGE: "[LOG MESSAGE] ${{ github.event.inputs.message }}"
      # Conditional set variable
      - name: Condtional
        run: |
          echo $GITHUB_ENV
          [[ ("${{ github.event.inputs.message }}" != "")]] && echo MSG="[SECOND MESSAGE] ${{ github.event.inputs.message }}" >> $GITHUB_ENV 
          echo $MSG
